# Generated by Django 5.1.2 on 2024-11-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_alter_product_options_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price']},
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
