# Generated by Django 5.1.2 on 2025-01-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_product_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
